import { StyleSheet } from "react-native";
import { moderateScale } from "../../../Utills/Scalling"; // Adjust path as needed

// This function will create styles based on the theme object from context
export const createPrinterSettingsStyles = (theme) => {
  const { COLORS, SIZES, FONTS } = theme;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
      padding: SIZES.padding,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: COLORS.background,
    },
    loadingText: {
      fontSize: moderateScale(SIZES.font),
      color: COLORS.textLight,
      marginTop: moderateScale(16),
      ...FONTS.font,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: moderateScale(20),
      paddingHorizontal: moderateScale(5), // Add some horizontal padding if needed
    },
    backButton: {
      backgroundColor: COLORS.secondary,
      width: moderateScale(44),
      height: moderateScale(44),
      borderRadius: moderateScale(22),
      justifyContent: "center",
      alignItems: "center",
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
    },
    backButtonText: {
      // You can remove this if using Icon component
    },
    mainTitle: {
      fontSize: moderateScale(SIZES.h4),
      fontWeight: "700",
      color: COLORS.title,
      flex: 1,
      textAlign: "center",
      marginHorizontal: moderateScale(10),
      ...FONTS.h4,
    },
    refreshButton: {
      backgroundColor: COLORS.primary,
      width: moderateScale(44),
      height: moderateScale(44),
      borderRadius: moderateScale(22),
      justifyContent: "center",
      alignItems: "center",
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
    },
    refreshButtonText: {
      // You can remove this if using Icon component
    },
    // Optional: Add disabled state styles
    disabledButton: {
      backgroundColor: COLORS.placeholder,
      opacity: 0.6,
    },
    currentPrinterSection: {
      backgroundColor: COLORS.primary,
      padding: SIZES.padding,
      borderRadius: SIZES.radius,
      marginBottom: moderateScale(16),
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
    },
    currentPrinterHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: moderateScale(8),
    },
    currentPrinterLabel: {
      fontSize: moderateScale(SIZES.fontSm),
      color: COLORS.buttonText,
      fontWeight: "600",
      opacity: 0.9,
      marginRight: moderateScale(8),
      ...FONTS.fontSm,
    },
    statusIndicator: {
      width: moderateScale(8),
      height: moderateScale(8),
      borderRadius: moderateScale(4),
      backgroundColor: COLORS.success,
    },
    currentPrinterName: {
      fontSize: moderateScale(SIZES.h5),
      color: COLORS.buttonText,
      fontWeight: "700",
      marginBottom: moderateScale(4),
      ...FONTS.h5,
    },
    currentPrinterAddress: {
      fontSize: moderateScale(SIZES.font),
      color: COLORS.buttonText,
      opacity: 0.9,
      marginBottom: moderateScale(4),
      ...FONTS.font,
    },
    clearCurrentButton: {
      backgroundColor: "rgba(255,255,255,0.2)",
      padding: moderateScale(10),
      borderRadius: SIZES.radius_sm,
      marginTop: moderateScale(8),
      alignSelf: "flex-start",
    },
    clearCurrentButtonText: {
      color: COLORS.buttonText,
      fontSize: moderateScale(SIZES.fontSm),
      fontWeight: "600",
      ...FONTS.fontSm,
    },
    formSection: {
      backgroundColor: COLORS.surface,
      padding: SIZES.padding,
      borderRadius: SIZES.radius,
      marginBottom: moderateScale(16),
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: 1,
      borderColor: COLORS.borderColor,
    },
    formHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: moderateScale(16),
    },
    sectionTitle: {
      fontSize: moderateScale(SIZES.h5),
      fontWeight: "600",
      color: COLORS.title,
      ...FONTS.h5,
    },
    cancelEditText: {
      color: COLORS.danger,
      fontSize: moderateScale(SIZES.fontSm),
      fontWeight: "600",
      ...FONTS.fontSm,
    },
    label: {
      fontSize: moderateScale(SIZES.font),
      color: COLORS.text,
      marginTop: moderateScale(16),
      marginBottom: moderateScale(5),
      fontWeight: "500",
      ...FONTS.font,
    },
    input: {
      borderWidth: 1,
      borderColor: COLORS.borderColor,
      borderRadius: SIZES.radius_sm,
      padding: moderateScale(12),
      backgroundColor: COLORS.input,
      color: COLORS.text,
      fontSize: moderateScale(SIZES.font),
      ...FONTS.font,
    },
    saveButton: {
      backgroundColor: COLORS.primary,
      padding: SIZES.padding,
      borderRadius: SIZES.radius,
      alignItems: "center",
      marginTop: moderateScale(16),
      minHeight: moderateScale(52),
      justifyContent: "center",
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
    },
    saveButtonDisabled: {
      backgroundColor: COLORS.placeholder,
      opacity: 0.6,
    },
    buttonText: {
      color: COLORS.buttonText,
      fontSize: moderateScale(SIZES.font),
      fontWeight: "600",
      ...FONTS.font,
    },
    savedPrintersSection: {
      backgroundColor: COLORS.surface,
      padding: SIZES.padding,
      borderRadius: SIZES.radius,
      marginBottom: moderateScale(16),
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: 1,
      borderColor: COLORS.borderColor,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: moderateScale(16),
    },
    sectionActions: {
      flexDirection: "row",
      gap: moderateScale(8),
    },
    manageButton: {
      backgroundColor: COLORS.secondary,
      paddingHorizontal: moderateScale(16),
      paddingVertical: moderateScale(8),
      borderRadius: SIZES.radius_sm,
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 1,
      shadowRadius: 2,
      elevation: 2,
    },
    clearAllButton: {
      backgroundColor: COLORS.danger,
      paddingHorizontal: moderateScale(16),
      paddingVertical: moderateScale(8),
      borderRadius: SIZES.radius_sm,
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 1,
      shadowRadius: 2,
      elevation: 2,
    },
    manageButtonText: {
      color: COLORS.buttonText,
      fontSize: moderateScale(SIZES.fontSm),
      fontWeight: "600",
      ...FONTS.fontSm,
    },
    clearAllButtonText: {
      color: COLORS.buttonText,
      fontSize: moderateScale(SIZES.fontSm),
      fontWeight: "600",
      ...FONTS.fontSm,
    },
    printerItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: SIZES.padding,
      borderWidth: 1,
      borderColor: COLORS.borderColor,
      backgroundColor: COLORS.surfaceVariant,
      marginBottom: moderateScale(8),
      borderRadius: SIZES.radius_sm,
    },
    currentPrinterItem: {
      borderLeftWidth: moderateScale(4),
      borderLeftColor: COLORS.primary,
      backgroundColor: COLORS.primaryLight,
    },
    printerInfo: {
      flex: 1,
      marginRight: moderateScale(16),
    },
    printerName: {
      fontSize: moderateScale(SIZES.font),
      color: COLORS.text,
      fontWeight: "600",
      marginBottom: moderateScale(2),
      ...FONTS.font,
    },
    printerAddress: {
      fontSize: moderateScale(SIZES.fontSm),
      color: COLORS.textLight,
      marginBottom: moderateScale(4),
      ...FONTS.fontSm,
    },
    printerMeta: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: moderateScale(8),
      marginTop: moderateScale(4),
    },
    currentBadge: {
      backgroundColor: COLORS.primary,
      paddingHorizontal: moderateScale(8),
      paddingVertical: moderateScale(2),
      borderRadius: SIZES.radius_sm,
    },
    currentBadgeText: {
      fontSize: moderateScale(SIZES.fontXs),
      color: COLORS.buttonText,
      fontWeight: "700",
      ...FONTS.fontXs,
    },
    printerActions: {
      flexDirection: "row",
      gap: moderateScale(6),
    },
    actionButton: {
      paddingHorizontal: moderateScale(10),
      paddingVertical: moderateScale(6),
      borderRadius: SIZES.radius_sm,
      minWidth: moderateScale(50),
      alignItems: "center",
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 1,
      shadowRadius: 2,
      elevation: 2,
    },
    selectButton: {
      backgroundColor: COLORS.success,
    },
    editButton: {
      backgroundColor: COLORS.info,
    },
    deleteButton: {
      backgroundColor: COLORS.danger,
    },
    actionButtonText: {
      color: COLORS.buttonText,
      fontSize: moderateScale(SIZES.fontXs),
      fontWeight: "600",
      ...FONTS.fontXs,
    },
    emptyState: {
      alignItems: "center",
      padding: moderateScale(32),
    },
    emptyStateIcon: {
      fontSize: moderateScale(48),
      marginBottom: moderateScale(16),
      color: COLORS.textLight,
    },
    emptyText: {
      fontSize: moderateScale(SIZES.font),
      color: COLORS.textLight,
      textAlign: "center",
      fontWeight: "500",
      ...FONTS.font,
    },
    emptySubtext: {
      fontSize: moderateScale(SIZES.fontSm),
      color: COLORS.textLight,
      textAlign: "center",
      marginTop: moderateScale(4),
      ...FONTS.fontSm,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: COLORS.overlay,
      justifyContent: "center",
      alignItems: "center",
      padding: SIZES.padding,
    },
    modalContent: {
      backgroundColor: COLORS.surface,
      borderRadius: SIZES.radius_lg,
      padding: SIZES.padding,
      width: "100%",
      maxHeight: "80%",
      borderWidth: 1,
      borderColor: COLORS.borderColor,
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 8,
      elevation: 5,
    },
    modalTitle: {
      fontSize: moderateScale(SIZES.h4),
      color: COLORS.title,
      marginBottom: moderateScale(16),
      textAlign: "center",
      fontWeight: "700",
      ...FONTS.h4,
    },
    searchInput: {
      borderWidth: 1,
      borderColor: COLORS.borderColor,
      borderRadius: SIZES.radius_sm,
      padding: moderateScale(12),
      backgroundColor: COLORS.input,
      color: COLORS.text,
      fontSize: moderateScale(SIZES.font),
      marginBottom: moderateScale(16),
      ...FONTS.font,
    },
    fullList: {
      maxHeight: moderateScale(400),
    },
    modalButtons: {
      marginTop: moderateScale(16),
    },
    secondaryButton: {
      backgroundColor: COLORS.secondary,
      padding: SIZES.padding,
      borderRadius: SIZES.radius,
      alignItems: "center",
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
    },
    confirmModal: {
      backgroundColor: COLORS.surface,
      borderRadius: SIZES.radius_lg,
      padding: SIZES.padding,
      width: "100%",
      alignItems: "center",
      borderWidth: 1,
      borderColor: COLORS.borderColor,
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 8,
      elevation: 5,
    },
    confirmTitle: {
      fontSize: moderateScale(SIZES.h4),
      color: COLORS.title,
      marginBottom: moderateScale(16),
      textAlign: "center",
      fontWeight: "700",
      ...FONTS.h4,
    },
    confirmMessage: {
      fontSize: moderateScale(SIZES.font),
      color: COLORS.text,
      textAlign: "center",
      marginBottom: moderateScale(24),
      lineHeight: moderateScale(22),
      ...FONTS.font,
    },
    confirmButtons: {
      flexDirection: "row",
      gap: moderateScale(12),
      width: "100%",
    },
    confirmButton: {
      flex: 1,
      padding: SIZES.padding,
      borderRadius: SIZES.radius,
      alignItems: "center",
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 4,
      elevation: 3,
    },
    cancelConfirmButton: {
      backgroundColor: COLORS.secondary,
    },
    deleteConfirmButton: {
      backgroundColor: COLORS.danger,
    },
    confirmButtonText: {
      color: COLORS.buttonText,
      fontSize: moderateScale(SIZES.font),
      fontWeight: "600",
      ...FONTS.font,
    },
  });
};

// Default export for convenience
export default createPrinterSettingsStyles;
